### ISSUE TITLE
Replication-factor is invalid error

### ISSUE THREAD

**Issue by snavruzov** [skcript/Kafka-Fabric-Network#4]
Hi,

I'm getting errors coming from orderer peer

```
orderer1.example.com      | 2019-01-25 10:40:56.699 UTC [orderer.consensus.kafka] startThread -> PANI 00b [channel: testchainid] Cannot post CONNECT message = kafka server: Replication-factor is invalid.
orderer1.example.com      | panic: [channel: testchainid] Cannot post CONNECT message = kafka server: Replication-factor is invalid.
orderer1.example.com      | 
orderer1.example.com      | goroutine 40 [running]:
orderer1.example.com      | github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000d0c60, 0x0, 0x0, 0x0)
orderer1.example.com      | 	/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x515
orderer1.example.com      | github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc00013a010, 0x4, 0xf77223, 0x2e, 0xc0002e5f88, 0x2, 0x2, 0x0, 0x0, 0x0)
orderer1.example.com      | 	/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0xf6
orderer1.example.com      | github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(0xc00013a010, 0xf77223, 0x2e, 0xc0002e5f88, 0x2, 0x2)
orderer1.example.com      | 	/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159 +0x79
orderer1.example.com      | github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panicf(0xc00013a020, 0xf77223, 0x2e, 0xc0002e5f88, 0x2, 0x2)
orderer1.example.com      | 	/opt/gopath/src/github.com/hyperledger/fabric/common/flogging/zap.go:74 +0x60
orderer1.example.com      | github.com/hyperledger/fabric/orderer/consensus/kafka.startThread(0xc00044a600)
orderer1.example.com      | 	/opt/gopath/src/github.com/hyperledger/fabric/orderer/consensus/kafka/chain.go:278 +0xddb
orderer1.example.com      | created by github.com/hyperledger/fabric/orderer/consensus/kafka.(*chainImpl).Start
orderer1.example.com      | 	/opt/gopath/src/github.com/hyperledger/fabric/orderer/consensus/kafka/chain.go:133 +0x3f
orderer1.example.com exited with code 2

```

While trying to create a channel, dropping SERVICE UNAVAILABLE errors obviously.

**Comment by snavruzov** [comment]
Fixed by modifying KAFKA_DEFAULT_REPLICATION_FACTOR=2 since I set two kafka clusters
